CN:
  anneal_clr_by_factor: 0.9
  backward_iters: 2
  clip_obs: 20
  cn_acs_select_name: null
  cn_batch_size: 3
  cn_eps: 1.0e-05
  cn_layers:
  - 20
  cn_learning_rate: 0.005
  cn_normalize: false
  cn_obs_select_name: null
  cn_reg_coeff: 0.5
  cn_target_kl_new_old: 2.5
  cn_target_kl_old_new: 10
  di_prior:
  - 0.9
  - 0.1
  mode: sample
  train_gail_lambda: false
PPO:
  LR_QN: 1e-3
  N_quantiles: 64
  batch_size: 64
  budget: 0
  clip_obs: 20
  clip_range: 0.2
  clip_range_cost_vf: null
  clip_range_reward_vf: null
  cost_gae_lambda: 0.95
  cost_gamma: 0.99
  cost_quantile: 48
  cost_vf_coef: 0.5
  derivative_control_coeff: 0
  derivative_cost_ema_alpha: 0.5
  ent_coef: 0.0
  eval_every: 2048
  forward_timesteps: 500
  integral_control_coeff: 0.0001
  learning_rate: 0.0003
  max_grad_norm: 0.5
  n_epochs: 2
  n_steps: 100
  penalty_initial_value: 1
  penalty_learning_rate: 0.1
  pid_delay: 1
  policy_layers:
  - 64
  - 64
  policy_name: DistributionalTwoCriticsMlpPolicy
  proportional_control_coeff: 10
  proportional_cost_ema_alpha: 0.5
  qnet_layers:
  - 256
  - 256
  reset_policy: false
  reward_gae_lambda: 0.95
  reward_gamma: 0.99
  reward_vf_coef: 0.5
  reward_vf_layers:
  - 64
  - 64
  sde_sample_freq: -1
  shared_layers: null
  target_kl: 0.01
  tau_update: 1e-2
  use_curiosity_driven_exploration: false
  use_sde: false
  warmup_timesteps: false
device: cpu
env:
  config_path: null
  cost_gamma: 0.99
  cost_info_str: cost
  dont_normalize_cost: false
  dont_normalize_obs: false
  dont_normalize_reward: false
  eval_env_id: HCWithPos-v0
  num_threads: 1
  record_info_input_dims:
  - 0
  record_info_names:
  - xpos
  reward_gamma: 0.99
  save_dir: ../save_model
  train_env_id: HCWithPos-v0
  use_cost: true
  visualize_info_ranges:
  - - -30
    - 30
group: VCIRL
multi_env: false
running:
  expert_path: ../data/expert_data/BlockedHalf-cheetah/
  expert_rollouts: 10
  n_eval_episodes: 10
  n_iters: 30
  sample_data_num: 500
  sample_rollouts: 10
  save_every: 1
  store_by_game: false
  store_sample_num: 1000
  store_sample_rollouts: 500
  use_buffer: true
task: VCIRL-HC
verbose: 2
