map_height: 7
map_width: 7
reward_states: [[6, 0]]
terminal_states: [[6, 0]]
unsafe_states: [[3,0], [3,1], [3,2], [3,3]]   # [(ui, uj) for ui in [3] for uj in [0, 1, 2, 3]]
start_states: [[0,0], [1,0], [2,0], [0,1], [1,1], [2,1]]   # s = [(ui, uj) for ui in [0, 1, 2] for uj in [0, 1]]
